### ISSUE TITLE
[UX] Wybranie fluentów nie powoduje wyświetlenia ich w menu rozwijanym

### ISSUE THREAD

**Issue by gczarnocki** [meoke/RW-Grupa-2#3]
![2018-06-06_22-36-35](https://user-images.githubusercontent.com/11662150/41063883-3da9852e-69da-11e8-88c1-c75dbbe2aa9f.gif)

**Comment by jakubiakm** [comment]
Zwróć uwagę na to, że w tej liście rozwijalnej można wybrać wiele fluentów przez co nie wszystkie będą widoczne w zwiniętej kontrolce. W takim wypadku wyglądałoby to nieelegancko. Zaznaczone fluenty można zobaczyć po kliknięciu w kontrolkę, więc myślę, że zmiana nie jest konieczna.

**Comment by admal** [comment]
Można by pisaćna kontrolce typu '~fluent1, fluent2'. A jak byłoby ich dużo to dać '...'.  Bo teraz jest nieczytelne, no ale to tylko UX ;)

**Comment by meoke** [comment]
Wyjaśnione - zamykam.
