### ISSUE TITLE
[Core] Można zanegować fluent więcej niż jeden raz podczas tworzenia scenariusza

### ISSUE THREAD

**Issue by gczarnocki** [meoke/RW-Grupa-2#4]
Walidacja wyrażenia np. `~~~~~~~~working_fridge` jest poprawna - czy parzysta liczba negacji oznacza, że wybrany jest fluent niezanegowany?

![image](https://user-images.githubusercontent.com/11662150/41064788-e17ea4a2-69dc-11e8-9d77-2f475da755df.png)

**Comment by jakubiakm** [comment]
Tak, parzysta liczba negacji oznacza, że wybrany fluent jest niezanegowany. Takie wyrażenia są poprawne i nie wpływają źle na działanie aplikacji, więc moim zdaniem może zostać jak jest.

**Comment by meoke** [comment]
Skoro jest ok - zamykam.
