### ISSUE TITLE
[Core] Dodanie dwóch zdań typu 'Causes' z zanegowanym (i nie) fluentem zawiesza program

### ISSUE THREAD

**Issue by gczarnocki** [meoke/RW-Grupa-2#5]
Historia numer 1. Dodatkowo, dodane zdanie: 'break by Fridge lasting 1 causes working_fridge`, co kłóci się z drugim zdaniem z dziedziny D.

Oczekiwany rezultat: wykrycie potencjalnie błędnego opisu dziedziny D w trakcie obliczeń scenariusza.
Aktualny rezultat: program zawiesza się i kończy błędem.

**Comment by mily94** [comment]
Done

**Comment by meoke** [comment]
Skoro zrobione - zamykam.
