### ISSUE TITLE
[UX] nie da się wprowadzić przykładu 4 (nie tylko release)

### ISSUE THREAD

**Issue by admal** [meoke/RW-Grupa-2#7]
Nie tylko _release_  jest niezgodne z syntaktyką, ale również nie da sie wprowadzic formuły _triggers_. Nie ma warunku _if_.
![image](https://user-images.githubusercontent.com/13138031/41127161-447e69ac-6aaa-11e8-8bcf-8b1bca8cdb74.png)
![image](https://user-images.githubusercontent.com/13138031/41127190-56103bc8-6aaa-11e8-972a-d77e904acf8c.png)

**Comment by meoke** [comment]
przykład poprawiony
