### ISSUE TITLE
[Core] dwa razy zdefiniowane zdanie z innym lastingiem crashuje

### ISSUE THREAD

**Issue by berentmich** [meoke/RW-Grupa-2#9]
Krótki opis:
dwa razy zdefiniowane zdanie z innym lastingiem crashuje
Sposób wywołania:
Definition
Actions: robi_sie 
Agents: janek 
Fluents: janek_zrobiony

Sentences
robi_sie by janek lasting 1 causes janek_zrobiony,
robi_sie by janek lasting 2 causes janek_zrobiony

Scenarios
Observations:
[wszystkie obserwacje]

Action occurrences:
[action:robi_sie,agent:janek,time:1]

Queries
Executetable Sc?

Spodziewany rezultat:
wykrycie potencjalnie błędnego opisu
Aktualny rezultat:
Crash

**Comment by meoke** [comment]
Już nie crashuje, choć powoduje inne błędy. Zamykam, rozwiążemy wewnętrznie.
